language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    .Build/bin/phpunit --configuration Tests/Functional/phpunit.xml;

